#!/usr/bin/env python3
"""Goal-achievement rollup — the lite tracking consumer for the operating model.

Reads goals.json, checks each KR's GitHub Issue state, writes STATUS.md with a
per-goal completion %. Dormant until goals.json has goals. No third-party deps.

Usage:
    python scripts/goal_rollup.py            # print to stdout
    python scripts/goal_rollup.py --write    # (re)write STATUS.md

See docs/goals.md and docs/operating-model.md.
"""
from __future__ import annotations

import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def issue_state(number: int) -> str:
    """Return 'open' / 'closed' / 'unknown' for a GitHub issue via gh."""
    try:
        out = subprocess.run(
            ["gh", "issue", "view", str(number), "--json", "state", "--jq", ".state"],
            capture_output=True, text=True, check=True,
        )
        return out.stdout.strip().lower() or "unknown"
    except Exception:  # gh missing / not authed / issue gone — stay dormant, don't crash
        return "unknown"


def render(goals: list) -> str:
    lines = [
        "# Goal status",
        "",
        "*Generated by `scripts/goal_rollup.py` — see [docs/goals.md](docs/goals.md).*",
        "",
    ]
    if not goals:
        lines.append(
            "No goals defined yet — `goals.json` is empty by design (goals are "
            "human-authored; see [docs/goals.md](docs/goals.md)). The rails "
            "(eval-gate, this rollup) are dormant-but-ready."
        )
        return "\n".join(lines) + "\n"
    for g in goals:
        krs = g.get("key_results", [])
        done = sum(
            1 for kr in krs
            if kr.get("issue") and issue_state(kr["issue"]) == "closed"
        )
        pct = round(100 * done / len(krs)) if krs else 0
        lines += [
            f"## {g.get('id', '?')} — {g.get('objective', '')}",
            "",
            f"**{pct}%** — {done}/{len(krs)} KRs achieved",
            "",
        ]
        for kr in krs:
            num = kr.get("issue")
            state = issue_state(num) if num else "no-issue"
            mark = "x" if state == "closed" else " "
            ref = f"#{num}" if num else "(unlinked)"
            lines.append(f"- [{mark}] `{kr.get('id', '?')}` {ref} — {kr.get('statement', '')}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    goals = json.loads((ROOT / "goals.json").read_text()).get("goals", [])
    out = render(goals)
    if "--write" in sys.argv:
        (ROOT / "STATUS.md").write_text(out)
        print("wrote STATUS.md")
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
